APT::FTPArchive::Release::Origin "strayfade's repo";
APT::FTPArchive::Release::Label "strayfade's repo";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "iphoneos-arm64 arm64 arm64e";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Mostly small QOL jailbreak tweaks by strayfade";
