APT::FTPArchive::Release::Origin "strayfade tweaks";
APT::FTPArchive::Release::Label "strayfade tweaks";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "iphoneos-arm64 arm64 arm64e";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "iOS jailbreak tweaks by strayfade and Noah";
