ARCHS = arm64 arm64e

include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = netsocket

netsocket_FILES = netsocket.mm
netsocket_CFLAGS = -fobjc-arc
netsocket_INSTALL_PATH = /Library/PreferenceBundles
netsocket_FRAMEWORKS = UIKit
netsocket_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk

internal-stage::
	$(ECHO_NOTHING)mkdir -p $(THEOS_STAGING_DIR)/Library/PreferenceLoader/Preferences$(ECHO_END)
	$(ECHO_NOTHING)cp entry.plist $(THEOS_STAGING_DIR)/Library/PreferenceLoader/Preferences/netsocket.plist$(ECHO_END)