#ifndef SMHIDUsages_h
#define SMHIDUsages_h

// USB HID keyboard usages (kHIDUsage_Keyboard*).
enum {
    kSMHIDUsage_KeyboardA = 0x04,
    kSMHIDUsage_KeyboardZ = 0x1D,
    kSMHIDUsage_Keyboard1 = 0x1E,
    kSMHIDUsage_Keyboard2 = 0x1F,
    kSMHIDUsage_Keyboard3 = 0x20,
    kSMHIDUsage_Keyboard4 = 0x21,
    kSMHIDUsage_Keyboard5 = 0x22,
    kSMHIDUsage_Keyboard6 = 0x23,
    kSMHIDUsage_Keyboard7 = 0x24,
    kSMHIDUsage_Keyboard8 = 0x25,
    kSMHIDUsage_Keyboard9 = 0x26,
    kSMHIDUsage_Keyboard0 = 0x27,
    kSMHIDUsage_KeyboardReturnOrEnter = 0x28,
    kSMHIDUsage_KeyboardEscape = 0x29,
    kSMHIDUsage_KeyboardDeleteOrBackspace = 0x2A,
    kSMHIDUsage_KeyboardTab = 0x2B,
    kSMHIDUsage_KeyboardSpacebar = 0x2C,
    kSMHIDUsage_KeyboardHyphen = 0x2D,
    kSMHIDUsage_KeyboardEqualSign = 0x2E,
    kSMHIDUsage_KeyboardOpenBracket = 0x2F,
    kSMHIDUsage_KeyboardCloseBracket = 0x30,
    kSMHIDUsage_KeyboardBackslash = 0x31,
    kSMHIDUsage_KeyboardSemicolon = 0x32,
    kSMHIDUsage_KeyboardQuote = 0x33,
    kSMHIDUsage_KeyboardGraveAccentAndTilde = 0x35,
    kSMHIDUsage_KeyboardComma = 0x36,
    kSMHIDUsage_KeyboardPeriod = 0x37,
    kSMHIDUsage_KeyboardSlash = 0x38,
    kSMHIDUsage_KeyboardCapsLock = 0x39,
    kSMHIDUsage_KeyboardF1 = 0x3A,
    kSMHIDUsage_KeyboardF12 = 0x45,
    kSMHIDUsage_KeyboardF13 = 0x68,
    kSMHIDUsage_KeyboardF24 = 0x73,
    kSMHIDUsage_KeyboardInsert = 0x49,
    kSMHIDUsage_KeyboardHome = 0x4A,
    kSMHIDUsage_KeyboardPageUp = 0x4B,
    kSMHIDUsage_KeyboardDeleteForward = 0x4C,
    kSMHIDUsage_KeyboardEnd = 0x4D,
    kSMHIDUsage_KeyboardPageDown = 0x4E,
    kSMHIDUsage_KeyboardRightArrow = 0x4F,
    kSMHIDUsage_KeyboardLeftArrow = 0x50,
    kSMHIDUsage_KeyboardDownArrow = 0x51,
    kSMHIDUsage_KeyboardUpArrow = 0x52,
    kSMHIDUsage_KeyboardKeypadNumLock = 0x53,
    kSMHIDUsage_KeyboardPause = 0x48,
    kSMHIDUsage_KeyboardLeftControl = 0xE0,
    kSMHIDUsage_KeyboardLeftShift = 0xE1,
    kSMHIDUsage_KeyboardLeftAlt = 0xE2,
    kSMHIDUsage_KeyboardLeftGUI = 0xE3,
    kSMHIDUsage_KeyboardRightControl = 0xE4,
    kSMHIDUsage_KeyboardRightShift = 0xE5,
    kSMHIDUsage_KeyboardRightAlt = 0xE6,
    kSMHIDUsage_KeyboardRightGUI = 0xE7,
    kSMHIDUsage_KeypadComma = 0x85,
};

enum {
    kSMHIDPage_KeyboardOrKeypad = 0x07,
};

#endif
