#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

FOUNDATION_EXPORT NSString *const kSCPasteboardTypeUTF8;
FOUNDATION_EXPORT NSString *const kSCPasteboardTypePlain;
FOUNDATION_EXPORT NSString *const kSCPasteboardTypePNG;
FOUNDATION_EXPORT NSString *const kSCPasteboardAutoGeneratedType;

void scInstallPasteboardPrivacyHooks(void);

NSInteger scPasteboardChangeCount(void);
NSData *scPasteboardReadTextData(void);
NSData *scPasteboardReadImagePNGData(void);
void scPasteboardApplyText(NSString *text);
void scPasteboardApplyImage(UIImage *image);
