#import "SCPasteboard.h"
#import <objc/message.h>
#import <stdatomic.h>
#import <substrate.h>

NSString *const kSCPasteboardTypeUTF8 = @"public.utf8-plain-text";
NSString *const kSCPasteboardTypePlain = @"public.plain-text";
NSString *const kSCPasteboardTypePNG = @"public.png";
NSString *const kSCPasteboardAutoGeneratedType = @"org.nspasteboard.AutoGeneratedType";

typedef NS_ENUM(NSInteger, _UIDataOwner) {
    _UIDataOwnerShared = 2,
};

@interface UIPasteboard (SCPrivate)
+ (void)_performAsDataOwner:(_UIDataOwner)owner block:(dispatch_block_t)block;
@end

static _Atomic int32_t scPasteboardSyncAccessDepth = 0;
static _Atomic int32_t scPasteboardReadInProgress = 0;

static void scPasteboardSyncAccessBegin(void) {
    atomic_fetch_add(&scPasteboardSyncAccessDepth, 1);
}

static void scPasteboardSyncAccessEnd(void) {
    int32_t depth = atomic_load(&scPasteboardSyncAccessDepth);
    if (depth > 0) {
        atomic_fetch_sub(&scPasteboardSyncAccessDepth, 1);
    }
}

BOOL scPasteboardShouldBypassPrivacyPrompts(void) {
    return atomic_load(&scPasteboardSyncAccessDepth) > 0;
}

static UIPasteboard *scGeneralPasteboard(void) {
    return [UIPasteboard generalPasteboard];
}

static void scPerformPasteboardWorkWithOwner(_UIDataOwner owner, dispatch_block_t block) {
    if (!block) {
        return;
    }

    Class pasteboardClass = [UIPasteboard class];
    SEL selector = @selector(_performAsDataOwner:block:);
    if ([pasteboardClass respondsToSelector:selector]) {
        void (*performAsDataOwner)(id, SEL, _UIDataOwner, dispatch_block_t) =
            (void (*)(id, SEL, _UIDataOwner, dispatch_block_t))[pasteboardClass methodForSelector:selector];
        performAsDataOwner(pasteboardClass, selector, owner, block);
        return;
    }

    block();
}

static NSData *scReadTextDirect(void) {
    UIPasteboard *pasteboard = scGeneralPasteboard();
    if (!pasteboard) {
        return nil;
    }

    NSData *data = [pasteboard dataForPasteboardType:kSCPasteboardTypeUTF8];
    if (data.length > 0) {
        return data;
    }
    return [pasteboard dataForPasteboardType:kSCPasteboardTypePlain];
}

static NSData *scReadImageDirect(void) {
    UIPasteboard *pasteboard = scGeneralPasteboard();
    if (!pasteboard) {
        return nil;
    }

    NSData *pngData = [pasteboard dataForPasteboardType:kSCPasteboardTypePNG];
    if (pngData.length > 0) {
        return pngData;
    }

    NSData *imageData = [pasteboard dataForPasteboardType:@"public.image"];
    if (imageData.length == 0) {
        return nil;
    }

    UIImage *image = [UIImage imageWithData:imageData];
    if (!image) {
        return nil;
    }
    return UIImagePNGRepresentation(image);
}

NSInteger scPasteboardChangeCount(void) {
    UIPasteboard *pasteboard = scGeneralPasteboard();
    return pasteboard ? pasteboard.changeCount : 0;
}

NSData *scPasteboardReadTextData(void) {
    if (atomic_exchange(&scPasteboardReadInProgress, 1) != 0) {
        return nil;
    }

    NSData *result = nil;
    scPasteboardSyncAccessBegin();
    @try {
        result = scReadTextDirect();
    } @catch (__unused NSException *exception) {
        result = nil;
    }
    scPasteboardSyncAccessEnd();

    atomic_store(&scPasteboardReadInProgress, 0);
    return result;
}

NSData *scPasteboardReadImagePNGData(void) {
    if (atomic_load(&scPasteboardReadInProgress) != 0) {
        return nil;
    }

    NSData *result = nil;
    scPasteboardSyncAccessBegin();
    @try {
        result = scReadImageDirect();
    } @catch (__unused NSException *exception) {
        result = nil;
    }
    scPasteboardSyncAccessEnd();
    return result;
}

static void scPasteboardApplyItems(NSArray<NSDictionary *> *items) {
    if (items.count == 0) {
        return;
    }

    scPasteboardSyncAccessBegin();
    scPerformPasteboardWorkWithOwner(_UIDataOwnerShared, ^{
        UIPasteboard *pasteboard = scGeneralPasteboard();
        if (!pasteboard) {
            return;
        }

        @try {
            NSDictionary *options = @{
                UIPasteboardOptionLocalOnly: @YES,
            };
            [pasteboard setItems:items options:options];
        } @catch (__unused NSException *exception) {
        }
    });
    scPasteboardSyncAccessEnd();
}

void scPasteboardApplyText(NSString *text) {
    if (text.length == 0) {
        return;
    }

    NSDictionary *item = @{
        kSCPasteboardTypeUTF8: text,
        kSCPasteboardAutoGeneratedType: [NSData data],
    };
    scPasteboardApplyItems(@[item]);
}

void scPasteboardApplyImage(UIImage *image) {
    if (!image) {
        return;
    }

    NSData *pngData = UIImagePNGRepresentation(image);
    if (pngData.length == 0) {
        return;
    }

    NSDictionary *item = @{
        kSCPasteboardTypePNG: pngData,
        kSCPasteboardAutoGeneratedType: [NSData data],
    };
    scPasteboardApplyItems(@[item]);
}

typedef BOOL (*SCBoolTypeIMP)(id, SEL, NSString *);
typedef BOOL (*SCBoolItemIMP)(id, SEL, id);
typedef BOOL (*SCBoolIMP)(id, SEL);
typedef void (*SCRequestAuthIMP)(id, SEL, NSArray *, void (^)(BOOL));
typedef void (*SCUserAuthIMP)(id, SEL, void (^)(BOOL));

static SCBoolTypeIMP orig_pasteboardTypeRequiresConsent = NULL;
static SCBoolItemIMP orig_itemMayRequireConsent = NULL;
static SCRequestAuthIMP orig_requestAuthorization = NULL;
static SCRequestAuthIMP orig_requestAuthorizationIfNeeded = NULL;
static SCUserAuthIMP orig_requestUserAuthorization = NULL;
static SCBoolIMP orig_shouldDisplayPrompt = NULL;

static BOOL repl_pasteboardTypeRequiresConsent(id self, SEL _cmd, NSString *type) {
    if (scPasteboardShouldBypassPrivacyPrompts()) {
        return NO;
    }
    return orig_pasteboardTypeRequiresConsent ? orig_pasteboardTypeRequiresConsent(self, _cmd, type) : NO;
}

static BOOL repl_itemMayRequireConsent(id self, SEL _cmd, id item) {
    if (scPasteboardShouldBypassPrivacyPrompts()) {
        return NO;
    }
    return orig_itemMayRequireConsent ? orig_itemMayRequireConsent(self, _cmd, item) : NO;
}

static void scCallAuthHandler(void (^handler)(BOOL)) {
    if (handler) {
        handler(YES);
    }
}

static void repl_requestAuthorization(id self, SEL _cmd, NSArray *types, void (^handler)(BOOL)) {
    if (scPasteboardShouldBypassPrivacyPrompts()) {
        scCallAuthHandler(handler);
        return;
    }
    if (orig_requestAuthorization) {
        orig_requestAuthorization(self, _cmd, types, handler);
    }
}

static void repl_requestAuthorizationIfNeeded(id self, SEL _cmd, NSArray *types, void (^handler)(BOOL)) {
    if (scPasteboardShouldBypassPrivacyPrompts()) {
        scCallAuthHandler(handler);
        return;
    }
    if (orig_requestAuthorizationIfNeeded) {
        orig_requestAuthorizationIfNeeded(self, _cmd, types, handler);
    }
}

static void repl_requestUserAuthorization(id self, SEL _cmd, void (^handler)(BOOL)) {
    if (scPasteboardShouldBypassPrivacyPrompts()) {
        scCallAuthHandler(handler);
        return;
    }
    if (orig_requestUserAuthorization) {
        orig_requestUserAuthorization(self, _cmd, handler);
    }
}

static BOOL repl_shouldDisplayPrompt(id self, SEL _cmd) {
    if (scPasteboardShouldBypassPrivacyPrompts()) {
        return NO;
    }
    return orig_shouldDisplayPrompt ? orig_shouldDisplayPrompt(self, _cmd) : NO;
}

static void scHookInstanceMethod(Class cls, const char *selectorName, IMP replacement, IMP *original) {
    SEL selector = sel_registerName(selectorName);
    Method method = class_getInstanceMethod(cls, selector);
    if (!method) {
        return;
    }
    MSHookMessageEx(cls, selector, replacement, (IMP *)original);
}

void scInstallPasteboardPrivacyHooks(void) {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        Class pasteboardClass = objc_getClass("UIPasteboard");
        if (!pasteboardClass) {
            return;
        }

        scHookInstanceMethod(pasteboardClass,
                             "_pasteboardTypeRequiresUIPasteboardAccessConsent:",
                             (IMP)repl_pasteboardTypeRequiresConsent,
                             (IMP *)&orig_pasteboardTypeRequiresConsent);
        scHookInstanceMethod(pasteboardClass,
                             "_itemMayRequireUIPasteboardAccessConsent:",
                             (IMP)repl_itemMayRequireConsent,
                             (IMP *)&orig_itemMayRequireConsent);
        scHookInstanceMethod(pasteboardClass,
                             "_requestAuthorizationForPasteboardAccessWithTypes:completionHandler:",
                             (IMP)repl_requestAuthorization,
                             (IMP *)&orig_requestAuthorization);
        scHookInstanceMethod(pasteboardClass,
                             "_requestAuthorizationIfNeededForTypes:completionHandler:",
                             (IMP)repl_requestAuthorizationIfNeeded,
                             (IMP *)&orig_requestAuthorizationIfNeeded);
        scHookInstanceMethod(pasteboardClass,
                             "_requestUserAuthorizationForPasteboardAccessWithCompletionHandler:",
                             (IMP)repl_requestUserAuthorization,
                             (IMP *)&orig_requestUserAuthorization);
        scHookInstanceMethod(pasteboardClass,
                             "_shouldDisplayUIKitPasteboardPrompt",
                             (IMP)repl_shouldDisplayPrompt,
                             (IMP *)&orig_shouldDisplayPrompt);
    });
}
